# Generated by Django 5.1.2 on 2024-11-10 07:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_remove_platform_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='type',
            field=models.ForeignKey(db_column='type_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='reviews.restauranttype'),
        ),
        migrations.AlterField(
            model_name='restaurantplatformanalysis',
            name='platform',
            field=models.ForeignKey(db_column='platform_id', on_delete=django.db.models.deletion.CASCADE, to='reviews.platform'),
        ),
        migrations.AlterField(
            model_name='restaurantplatformanalysis',
            name='restaurant',
            field=models.ForeignKey(db_column='restaurant_id', on_delete=django.db.models.deletion.CASCADE, to='reviews.restaurant'),
        ),
        migrations.AlterField(
            model_name='restaurantplatformrating',
            name='platform',
            field=models.ForeignKey(db_column='platform_id', on_delete=django.db.models.deletion.CASCADE, to='reviews.platform'),
        ),
        migrations.AlterField(
            model_name='restaurantplatformrating',
            name='restaurant',
            field=models.ForeignKey(db_column='restaurant_id', on_delete=django.db.models.deletion.CASCADE, to='reviews.restaurant'),
        ),
        migrations.AlterField(
            model_name='restaurantplatformsummary',
            name='platform',
            field=models.ForeignKey(db_column='platform_id', on_delete=django.db.models.deletion.CASCADE, to='reviews.platform'),
        ),
        migrations.AlterField(
            model_name='restaurantplatformsummary',
            name='restaurant',
            field=models.ForeignKey(db_column='restaurant_id', on_delete=django.db.models.deletion.CASCADE, to='reviews.restaurant'),
        ),
        migrations.AlterField(
            model_name='review',
            name='ai_sentiment',
            field=models.ForeignKey(db_column='ai_sentiment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_sentiment_reviews', to='reviews.sentiment'),
        ),
        migrations.AlterField(
            model_name='review',
            name='author',
            field=models.ForeignKey(db_column='author_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='reviews.reviewauthor'),
        ),
        migrations.AlterField(
            model_name='review',
            name='manual_sentiment',
            field=models.ForeignKey(db_column='manual_sentiment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manual_sentiment_reviews', to='reviews.sentiment'),
        ),
        migrations.AlterField(
            model_name='review',
            name='restaurant',
            field=models.ForeignKey(db_column='restaurant_id', on_delete=django.db.models.deletion.CASCADE, to='reviews.restaurant'),
        ),
        migrations.AlterField(
            model_name='reviewauthor',
            name='platform',
            field=models.ForeignKey(db_column='platform_id', on_delete=django.db.models.deletion.CASCADE, to='reviews.platform'),
        ),
        migrations.AlterField(
            model_name='sentiment',
            name='code',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterModelTable(
            name='platform',
            table='platforms',
        ),
        migrations.AlterModelTable(
            name='restaurant',
            table='restaurants',
        ),
        migrations.AlterModelTable(
            name='restaurantplatformanalysis',
            table='restaurant_platform_analysis',
        ),
        migrations.AlterModelTable(
            name='restaurantplatformrating',
            table='restaurant_platform_ratings',
        ),
        migrations.AlterModelTable(
            name='restaurantplatformsummary',
            table='restaurant_platform_summaries',
        ),
        migrations.AlterModelTable(
            name='restauranttype',
            table='restaurant_types',
        ),
        migrations.AlterModelTable(
            name='review',
            table='reviews',
        ),
        migrations.AlterModelTable(
            name='reviewauthor',
            table='review_authors',
        ),
        migrations.AlterModelTable(
            name='sentiment',
            table='sentiments',
        ),
        migrations.CreateModel(
            name='RestaurantPlatformInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('identifier', models.CharField(max_length=255)),
                ('platform', models.ForeignKey(db_column='platform_id', on_delete=django.db.models.deletion.CASCADE, to='reviews.platform')),
                ('restaurant', models.ForeignKey(db_column='restaurant_id', on_delete=django.db.models.deletion.CASCADE, to='reviews.restaurant')),
            ],
            options={
                'db_table': 'restaurant_platform_info',
                'unique_together': {('restaurant', 'platform')},
            },
        ),
        migrations.DeleteModel(
            name='RestaurantPlatformDescription',
        ),
    ]
