# Generated by Django 5.1.2 on 2024-11-10 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_rename_address_restaurant_common_address_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='detail_address',
            new_name='jibun_address',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='road_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
