# Generated by Django 5.1.2 on 2024-11-10 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_rename_detail_address_restaurant_jibun_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantplatforminfo',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='restaurantplatforminfo',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
