# Generated by Django 5.1.2 on 2024-11-10 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0006_restaurantplatforminfo_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantplatforminfo',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
