# Generated by Django 5.1.2 on 2024-11-11 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0007_alter_restaurantplatforminfo_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='selected_menu',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
