# Generated by Django 5.1.2 on 2024-11-11 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0008_review_selected_menu'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='has_image',
            field=models.BooleanField(default=False),
        ),
    ]
