# Generated by Django 5.1.2 on 2024-11-11 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0009_review_has_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantplatforminfo',
            name='last_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
