# Generated by Django 5.1.2 on 2024-11-11 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0010_restaurantplatforminfo_last_updated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewauthor',
            name='nickname',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
