# Generated by Django 5.1.2 on 2024-11-15 14:30

from django.db import migrations

def copy_latitude_longitude(apps, schema_editor):
    Restaurant = apps.get_model('reviews', 'Restaurant')
    RestaurantPlatformInfo = apps.get_model('reviews', 'RestaurantPlatformInfo')

    # platform_id=1인 RestaurantPlatformInfo 항목 필터링
    platform_info_entries = RestaurantPlatformInfo.objects.filter(platform_id=1)

    for entry in platform_info_entries:
        # 연관된 Restaurant 인스턴스 가져오기
        restaurant = entry.restaurant

        # latitude와 longitude가 None이 아닌 경우 복사
        if entry.latitude is not None and entry.longitude is not None:
            restaurant.latitude = entry.latitude
            restaurant.longitude = entry.longitude
            restaurant.save()

class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0017_restaurant_latitude_restaurant_longitude'),
    ]

    operations = [
        migrations.RunPython(copy_latitude_longitude),
    ]
