# Generated by Django 5.1.2 on 2024-11-15 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0018_auto_20241115_2330'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurantplatforminfo',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='restaurantplatforminfo',
            name='longitude',
        ),
    ]
