# Generated by Django 5.1.2 on 2024-11-19 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0019_remove_restaurantplatforminfo_latitude_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='manual_label_attempted',
            new_name='manual_sentiment_label_attempted',
        ),
        migrations.AddField(
            model_name='review',
            name='manual_true_label_attempted',
            field=models.BooleanField(default=False),
        ),
    ]
