# Generated by Django 5.1.2 on 2024-11-26 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0023_reviewextra_manual_is_true_review_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ReviewExtra',
            new_name='ExtraReview',
        ),
        migrations.AlterModelTable(
            name='extrareview',
            table='extra_reviews',
        ),
    ]
